networks:
  dev:
    driver: bridge

services:
  wvb-challenge-app:
    container_name: docker-ums
    ports:
      - "3001:3000"
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - dev